import "@/styles/globals.css";
import { PreloadFonts } from "@/components/Preload";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <PreloadFonts />
      </head>
      <body className="bg-cyan-900">{children}</body>
    </html>
  );
}
